run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - godot
    - gofumpt
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: package-comments
        arguments:
          - style: "// Package"
      - name: var-naming
        arguments:
          - checkRename
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
    - path: _test\.go
      text: "weak cryptographic primitive"
      linters:
        - gosec
    - path: _test\.go
      text: "potential file inclusion via variable"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
